services:
  app:
    image: gihyeon21/simple-updown:latest
    ports:
      - "9000:9000"
    volumes:
      - /path/to/dir:/app/uploads
    environment:
      - STORAGE_TYPE=local
    restart: unless-stopped
    container_name: file-storage-app
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

